import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    // Layout translations
    title: 'SmartMine',
    subtitle: 'AI & Automation',
    dashboard: 'Dashboard',
    vehicleEntry: 'Vehicle Entry',
    aiDetection: 'AI Detection',
    weighbridge: 'Weighbridge',
    inventory: 'Inventory',
    customers: 'Customers',
    employees: 'Employees',
    billing: 'Billing',
    reports: 'Reports',
    system: 'System',
    role: 'Role',
    language: 'Language',
    logout: 'Logout',
    search: 'Search...',
    
    // Dashboard translations
    totalVehicles: 'Total Vehicles',
    activeOperations: 'Active Operations',
    todayRevenue: 'Today\'s Revenue',
    pendingBills: 'Pending Bills',
    recentActivities: 'Recent Activities',
    quickActions: 'Quick Actions',
    registerVehicle: 'Register Vehicle',
    newWeighment: 'New Weighment',
    generateBill: 'Generate Bill',
    viewReports: 'View Reports',
    
    // Inventory translations
    stockOverview: 'Stock Overview',
    totalItems: 'Total Items',
    lowStock: 'Low Stock',
    outOfStock: 'Out of Stock',
    addNewItem: 'Add New Item',
    materialName: 'Material Name',
    availableQuantity: 'Available Quantity',
    shiftedQuantity: 'Shifted Quantity',
    remainingStock: 'Remaining Stock',
    unit: 'Unit',
    location: 'Location',
    submit: 'Submit',
    cancel: 'Cancel',
    actions: 'Actions',
    availableItems: 'Available Items',
    shiftedItems: 'Shifted Items',
    addEntry: 'Add Entry',
    manualEntry: 'Manual Entry',
    
    // Customer Management translations
    customerManagement: 'Customer Management',
    manageCustomerAccounts: 'Manage customer accounts and relationships',
    addCustomer: 'Add Customer',
    totalCustomers: 'Total Customers',
    totalOrders: 'Total Orders',
    totalRevenue: 'Total Revenue',
    recentActivity: 'Recent Activity',
    allCustomers: 'All Customers',
    customerId: 'Customer ID',
    company: 'Company',
    contact: 'Contact',
    phone: 'Phone',
    orders: 'Orders',
    value: 'Value',
    status: 'Status',
    active: 'Active',
    inactive: 'Inactive',
    newOrderPlaced: 'New order placed',
    paymentReceived: 'Payment received',
    deliveryCompleted: 'Delivery completed',
    
    // Billing translations
    billingInvoicing: 'Billing & Invoicing',
    manageInvoicesPayment: 'Manage invoices and payment tracking',
    createInvoice: 'Create Invoice',
    totalInvoices: 'Total Invoices',
    paidInvoices: 'Paid Invoices',
    pending: 'Pending',
    thisMonth: 'This month',
    collected: 'Collected',
    outstanding: 'Outstanding',
    allInvoices: 'All Invoices',
    invoiceId: 'Invoice ID',
    vehicle: 'Vehicle',
    material: 'Material',
    netWeight: 'Net Weight',
    rate: 'Rate',
    amount: 'Amount',
    date: 'Date',
    dueDate: 'Due Date',
    generate: 'Generate',
    print: 'Print',
    paid: 'Paid',
    
    // Employee translations
    employeeManagement: 'Employee Management',
    manageStaffRoles: 'Manage staff members and role assignments',
    addEmployee: 'Add Employee',
    totalEmployees: 'Total Employees',
    operators: 'Operators',
    departments: 'Departments',
    employeeDirectory: 'Employee Directory',
    allEmployees: 'All Employees',
    employeeId: 'Employee ID',
    name: 'Name',
    department: 'Department',
    email: 'Email',
    joinDate: 'Join Date',
    rolePermissions: 'Role Permissions',
    permissions: 'Permissions',
    
    // Vehicle Entry translations
    activeVehicles: 'Active Vehicles',
    startScanning: 'Start Scanning',
    recentEntries: 'Recent Entries',
    vehicleId: 'Vehicle ID',
    driver: 'Driver',
    weight: 'Weight',
    time: 'Time',
    type: 'Type',
    inTransit: 'In Transit',
    loading: 'Loading',
    weighing: 'Weighing',
    unloading: 'Unloading',
    manual: 'Manual',
    nfcTag: 'NFC Tag',
    lastEntry: 'Last Entry',
    
    // Weighbridge translations
    weighbridgeManagement: 'Weighbridge Management',
    realTimeWeighing: 'Real-time vehicle weighing and tracking',
    vehiclesToday: 'Vehicles Today',
    totalWeight: 'Total Weight',
    avgWeight: 'Avg Weight',
    recentWeighings: 'Recent Weighings',
    tareWeight: 'Tare Weight',
    grossWeight: 'Gross Weight',
    startWeighing: 'Start Weighing',
    complete: 'Complete',
    currentWeight: 'Current Weight',
    
    // Product Detection translations
    aiProductDetection: 'AI Product Detection',
    materialIdentification: 'Real-time material identification and quality analysis',
    confidence: 'Confidence',
    recentDetections: 'Recent Detections',
    batch: 'Batch',
    quality: 'Quality',
    scan: 'Scan',
    fraudAlert: 'Fraud Alert',
    high: 'High',
    medium: 'Medium',
    low: 'Low',
    
    // Reports translations
    productionReports: 'Production Reports',
    analyticsInsights: 'Comprehensive analytics and insights',
    downloadReport: 'Download Report',
    keyInsights: 'Key Insights',
    monthlyTrends: 'Monthly Trends',
    performance: 'Performance',
    productionData: 'Production Data',
    detectionAccuracy: 'Detection Accuracy',
    materialDistribution: 'Material Distribution',
    
    // System Architecture translations
    systemArchitecture: 'System Architecture',
    systemOverview: 'Complete system overview and infrastructure',
    hardwareIntegration: 'Hardware Integration',
    securityFeatures: 'Security Features',
    online: 'Online',
    offline: 'Offline',
    
    // Common
    save: 'Save',
    edit: 'Edit',
    delete: 'Delete',
    view: 'View',
    close: 'Close',
    confirm: 'Confirm',
  },
  hi: {
    // Layout translations
    title: 'स्मार्ट माइन्स',
    subtitle: 'AI और स्वचालन',
    dashboard: 'डैशबोर्ड',
    vehicleEntry: 'वाहन प्रवेश',
    aiDetection: 'AI पहचान',
    weighbridge: 'वेब्रिज',
    inventory: 'इन्वेंटरी',
    customers: 'ग्राहक',
    employees: 'कर्मचारी',
    billing: 'बिलिंग',
    reports: 'रिपोर्ट',
    system: 'सिस्टम',
    role: 'भूमिका',
    language: 'भाषा',
    logout: 'लॉगआउट',
    search: 'खोजें...',
    
    // Dashboard translations
    totalVehicles: 'कुल वाहन',
    activeOperations: 'सक्रिय कार्य',
    todayRevenue: 'आज का राजस्व',
    pendingBills: 'लंबित बिल',
    recentActivities: 'हाल की गतिविधियां',
    quickActions: 'त्वरित कार्य',
    registerVehicle: 'वाहन पंजीकृत करें',
    newWeighment: 'नया वजन',
    generateBill: 'बिल बनाएं',
    viewReports: 'रिपोर्ट देखें',
    
    // Inventory translations
    stockOverview: 'स्टॉक अवलोकन',
    totalItems: 'कुल आइटम',
    lowStock: 'कम स्टॉक',
    outOfStock: 'स्टॉक खत्म',
    addNewItem: 'नया आइटम जोड़ें',
    materialName: 'सामग्री का नाम',
    availableQuantity: 'उपलब्ध मात्रा',
    shiftedQuantity: 'स्थानांतरित मात्रा',
    remainingStock: 'शेष स्टॉक',
    unit: 'इकाई',
    location: 'स्थान',
    submit: 'जमा करें',
    cancel: 'रद्द करें',
    actions: 'क्रियाएं',
    availableItems: 'उपलब्ध आइटम',
    shiftedItems: 'स्थानांतरित आइटम',
    addEntry: 'प्रविष्टि जोड़ें',
    manualEntry: 'मैनुअल प्रविष्टि',
    
    // Customer Management translations
    customerManagement: 'ग्राहक प्रबंधन',
    manageCustomerAccounts: 'ग्राहक खातों और संबंधों का प्रबंधन करें',
    addCustomer: 'ग्राहक जोड़ें',
    totalCustomers: 'कुल ग्राहक',
    totalOrders: 'कुल ऑर्डर',
    totalRevenue: 'कुल राजस्व',
    recentActivity: 'हाल की गतिविधि',
    allCustomers: 'सभी ग्राहक',
    customerId: 'ग्राहक आईडी',
    company: 'कंपनी',
    contact: 'संपर्क',
    phone: 'फोन',
    orders: 'ऑर्डर',
    value: 'मूल्य',
    status: 'स्थिति',
    active: 'सक्रिय',
    inactive: 'निष्क्रिय',
    newOrderPlaced: 'नया ऑर्डर दिया गया',
    paymentReceived: 'भुगतान प्राप्त हुआ',
    deliveryCompleted: 'डिलीवरी पूरी हुई',
    
    // Billing translations
    billingInvoicing: 'बिलिंग और चालान',
    manageInvoicesPayment: 'चालान और भुगतान ट्रैकिंग प्रबंधित करें',
    createInvoice: 'चालान बनाएं',
    totalInvoices: 'कुल चालान',
    paidInvoices: 'भुगतान किए गए चालान',
    pending: 'लंबित',
    thisMonth: 'इस महीने',
    collected: 'एकत्रित',
    outstanding: 'बकाया',
    allInvoices: 'सभी चालान',
    invoiceId: 'चालान आईडी',
    vehicle: 'वाहन',
    material: 'सामग्री',
    netWeight: 'शुद्ध वजन',
    rate: 'दर',
    amount: 'राशि',
    date: 'तारीख',
    dueDate: 'नियत तारीख',
    generate: 'बनाएं',
    print: 'प्रिंट करें',
    paid: 'भुगतान किया',
    
    // Employee translations
    employeeManagement: 'कर्मचारी प्रबंधन',
    manageStaffRoles: 'कर्मचारियों और भूमिका असाइनमेंट को प्रबंधित करें',
    addEmployee: 'कर्मचारी जोड़ें',
    totalEmployees: 'कुल कर्मचारी',
    operators: 'ऑपरेटर',
    departments: 'विभाग',
    employeeDirectory: 'कर्मचारी निर्देशिका',
    allEmployees: 'सभी कर्मचारी',
    employeeId: 'कर्मचारी आईडी',
    name: 'नाम',
    department: 'विभाग',
    email: 'ईमेल',
    joinDate: 'शामिल होने की तारीख',
    rolePermissions: 'भूमिका अनुमतियां',
    permissions: 'अनुमतियां',
    
    // Vehicle Entry translations
    activeVehicles: 'सक्रिय वाहन',
    startScanning: 'स्कैनिंग शुरू करें',
    recentEntries: 'हाल की प्रविष्टियां',
    vehicleId: 'वाहन आईडी',
    driver: 'चालक',
    weight: 'वजन',
    time: 'समय',
    type: 'प्रकार',
    inTransit: 'ट्रांजिट में',
    loading: 'लोड हो रहा है',
    weighing: 'तौला जा रहा है',
    unloading: 'उतार रहा है',
    manual: 'मैनुअल',
    nfcTag: 'NFC टैग',
    lastEntry: 'अंतिम प्रविष्टि',
    
    // Weighbridge translations
    weighbridgeManagement: 'वेब्रिज प्रबंधन',
    realTimeWeighing: 'रियल-टाइम वाहन तौल और ट्रैकिंग',
    vehiclesToday: 'आज के वाहन',
    totalWeight: 'कुल वजन',
    avgWeight: 'औसत वजन',
    recentWeighings: 'हाल की तौल',
    tareWeight: 'खाली वजन',
    grossWeight: 'सकल वजन',
    startWeighing: 'तौल शुरू करें',
    complete: 'पूर्ण',
    currentWeight: 'वर्तमान वजन',
    
    // Product Detection translations
    aiProductDetection: 'AI उत्पाद पहचान',
    materialIdentification: 'रियल-टाइम सामग्री पहचान और गुणवत्ता विश्लेषण',
    confidence: 'विश्वास',
    recentDetections: 'हाल की पहचान',
    batch: 'बैच',
    quality: 'गुणवत्ता',
    scan: 'स्कैन करें',
    fraudAlert: 'धोखाधड़ी चेतावनी',
    high: 'उच्च',
    medium: 'मध्यम',
    low: 'कम',
    
    // Reports translations
    productionReports: 'उत्पादन रिपोर्ट',
    analyticsInsights: 'व्यापक विश्लेषण और अंतर्दृष्टि',
    downloadReport: 'रिपोर्ट डाउनलोड करें',
    keyInsights: 'मुख्य अंतर्दृष्टि',
    monthlyTrends: 'मासिक रुझान',
    performance: 'प्रदर्शन',
    productionData: 'उत्पादन डेटा',
    detectionAccuracy: 'पहचान सटीकता',
    materialDistribution: 'सामग्री वितरण',
    
    // System Architecture translations
    systemArchitecture: 'सिस्टम आर्किटेक्चर',
    systemOverview: 'पूर्ण सिस्टम अवलोकन और बुनियादी ढांचा',
    hardwareIntegration: 'हार्डवेयर एकीकरण',
    securityFeatures: 'सुरक्षा विशेषताएं',
    online: 'ऑनलाइन',
    offline: 'ऑफलाइन',
    
    // Common
    save: 'सहेजें',
    edit: 'संपादित करें',
    delete: 'हटाएं',
    view: 'देखें',
    close: 'बंद करें',
    confirm: 'पुष्टि करें',
  },
  te: {
    // Layout translations
    title: 'స్మార్ట్ మైన్స్',
    subtitle: 'AI & ఆటోమేషన్',
    dashboard: 'డాష్‌బోర్డ్',
    vehicleEntry: 'వాహన ప్రవేశం',
    aiDetection: 'AI గుర్తింపు',
    weighbridge: 'వెయిబ్రిడ్జ్',
    inventory: 'ఇన్వెంటరీ',
    customers: 'కస్టమర్లు',
    employees: 'ఉద్యోగులు',
    billing: 'బిల్లింగ్',
    reports: 'రిపోర్ట్లు',
    system: 'సిస్టమ్',
    role: 'పాత్ర',
    language: 'భాష',
    logout: 'లాగౌట్',
    search: 'వెతకండి...',
    
    // Dashboard translations
    totalVehicles: 'మొత్తం వాహనాలు',
    activeOperations: 'క్రియాశీల కార్యకలాపాలు',
    todayRevenue: 'నేటి ఆదాయం',
    pendingBills: 'పెండింగ్ బిల్లులు',
    recentActivities: 'ఇటీవలి కార్యకలాపాలు',
    quickActions: 'శీఘ్ర చర్యలు',
    registerVehicle: 'వాహనాన్ని నమోదు చేయండి',
    newWeighment: 'కొత్త బరువు',
    generateBill: 'బిల్లు రూపొందించండి',
    viewReports: 'నివేదికలను చూడండి',
    
    // Inventory translations
    stockOverview: 'స్టాక్ అవలోకనం',
    totalItems: 'మొత్తం వస్తువులు',
    lowStock: 'తక్కువ స్టాక్',
    outOfStock: 'స్టాక్ అయిపోయింది',
    addNewItem: 'కొత్త వస్తువును జోడించండి',
    materialName: 'మెటీరియల్ పేరు',
    availableQuantity: 'అందుబాటులో ఉన్న పరిమాణం',
    shiftedQuantity: 'మార్చబడిన పరిమాణం',
    remainingStock: 'మిగిలిన స్టాక్',
    unit: 'యూనిట్',
    location: 'స్థానం',
    submit: 'సమర్పించు',
    cancel: 'రద్దు చేయి',
    actions: 'చర్యలు',
    availableItems: 'అందుబాటులో ఉన్న వస్తువులు',
    shiftedItems: 'మార్చబడిన వస్తువులు',
    addEntry: 'ఎంట్రీ జోడించండి',
    manualEntry: 'మాన్యువల్ ఎంట్రీ',
    
    // Customer Management translations
    customerManagement: 'కస్టమర్ నిర్వహణ',
    manageCustomerAccounts: 'కస్టమర్ ఖాతాలు మరియు సంబంధాలను నిర్వహించండి',
    addCustomer: 'కస్టమర్ జోడించండి',
    totalCustomers: 'మొత్తం కస్టమర్లు',
    totalOrders: 'మొత్తం ఆర్డర్లు',
    totalRevenue: 'మొత్తం రాబడి',
    recentActivity: 'ఇటీవలి కార్యకలాపం',
    allCustomers: 'అన్ని కస్టమర్లు',
    customerId: 'కస్టమర్ ID',
    company: 'కంపెనీ',
    contact: 'సంప్రదింపు',
    phone: 'ఫోన్',
    orders: 'ఆర్డర్లు',
    value: 'విలువ',
    status: 'స్థితి',
    active: 'క్రియాశీలం',
    inactive: 'నిష్క్రియం',
    newOrderPlaced: 'కొత్త ఆర్డర్ ఇచ్చారు',
    paymentReceived: 'చెల్లింపు అందింది',
    deliveryCompleted: 'డెలివరీ పూర్తయింది',
    
    // Billing translations
    billingInvoicing: 'బిల్లింగ్ & ఇన్వాయిసింగ్',
    manageInvoicesPayment: 'ఇన్వాయిస్‌లు మరియు చెల్లింపు ట్రాకింగ్‌ను నిర్వహించండి',
    createInvoice: 'ఇన్వాయిస్ సృష్టించండి',
    totalInvoices: 'మొత్తం ఇన్వాయిస్‌లు',
    paidInvoices: 'చెల్లించిన ఇన్వాయిస్‌లు',
    pending: 'పెండింగ్',
    thisMonth: 'ఈ నెల',
    collected: 'సేకరించబడింది',
    outstanding: 'బాకీ',
    allInvoices: 'అన్ని ఇన్వాయిస్‌లు',
    invoiceId: 'ఇన్వాయిస్ ID',
    vehicle: 'వాహనం',
    material: 'మెటీరియల్',
    netWeight: 'నికర బరువు',
    rate: 'రేటు',
    amount: 'మొత్తం',
    date: 'తేదీ',
    dueDate: 'గడువు తేదీ',
    generate: 'రూపొందించు',
    print: 'ప్రింట్ చేయి',
    paid: 'చెల్లించబడింది',
    
    // Employee translations
    employeeManagement: 'ఉద్యోగి నిర్వహణ',
    manageStaffRoles: 'సిబ్బంది సభ్యులు మరియు పాత్ర కేటాయింపులను నిర్వహించండి',
    addEmployee: 'ఉద్యోగిని జోడించండి',
    totalEmployees: 'మొత్తం ఉద్యోగులు',
    operators: 'ఆపరేటర్లు',
    departments: 'విభాగాలు',
    employeeDirectory: 'ఉద్యోగి డైరెక్టరీ',
    allEmployees: 'అన్ని ఉద్యోగులు',
    employeeId: 'ఉద్యోగి ID',
    name: 'పేరు',
    department: 'విభాగం',
    email: 'ఇమెయిల్',
    joinDate: 'చేరిన తేదీ',
    rolePermissions: 'పాత్ర అనుమతులు',
    permissions: 'అనుమతులు',
    
    // Vehicle Entry translations
    activeVehicles: 'క్రియాశీల వాహనాలు',
    startScanning: 'స్కానింగ్ ప్రారంభించండి',
    recentEntries: 'ఇటీవలి ఎంట్రీలు',
    vehicleId: 'వాహన ID',
    driver: 'డ్రైవర్',
    weight: 'బరువు',
    time: 'సమయం',
    type: 'రకం',
    inTransit: 'ట్రాన్సిట్‌లో',
    loading: 'లోడ్ చేస్తోంది',
    weighing: 'తూకం కొలుస్తోంది',
    unloading: 'దింపుతోంది',
    manual: 'మాన్యువల్',
    nfcTag: 'NFC ట్యాగ్',
    lastEntry: 'చివరి ఎంట్రీ',
    
    // Weighbridge translations
    weighbridgeManagement: 'వెయిబ్రిడ్జ్ నిర్వహణ',
    realTimeWeighing: 'రియల్-టైమ్ వాహన తూకం మరియు ట్రాకింగ్',
    vehiclesToday: 'నేటి వాహనాలు',
    totalWeight: 'మొత్తం బరువు',
    avgWeight: 'సగటు బరువు',
    recentWeighings: 'ఇటీవలి తూకాలు',
    tareWeight: 'ఖాళీ బరువు',
    grossWeight: 'మొత్తం బరువు',
    startWeighing: 'తూకం ప్రారంభించండి',
    complete: 'పూర్తయింది',
    currentWeight: 'ప్రస్తుత బరువు',
    
    // Product Detection translations
    aiProductDetection: 'AI ఉత్పత్తి గుర్తింపు',
    materialIdentification: 'రియల్-టైమ్ మెటీరియల్ గుర్తింపు మరియు నాణ్యత విశ్లేషణ',
    confidence: 'నమ్మకం',
    recentDetections: 'ఇటీవలి గుర్తింపులు',
    batch: 'బ్యాచ్',
    quality: 'నాణ్యత',
    scan: 'స్కాన్ చేయి',
    fraudAlert: 'మోసం హెచ్చరిక',
    high: 'అధికం',
    medium: 'మధ్యస్థం',
    low: 'తక్కువ',
    
    // Reports translations
    productionReports: 'ఉత్పత్తి నివేదికలు',
    analyticsInsights: 'సమగ్ర విశ్లేషణ మరియు అంతర్దృష్టులు',
    downloadReport: 'నివేదికను డౌన్‌లోడ్ చేయండి',
    keyInsights: 'ముఖ్య అంతర్దృష్టులు',
    monthlyTrends: 'నెలవారీ ధోరణులు',
    performance: 'పనితీరు',
    productionData: 'ఉత్పత్తి డేటా',
    detectionAccuracy: 'గుర్తింపు ఖచ్చితత్వం',
    materialDistribution: 'మెటీరియల్ పంపిణీ',
    
    // System Architecture translations
    systemArchitecture: 'సిస్టమ్ ఆర్కిటెక్చర్',
    systemOverview: 'పూర్తి సిస్టమ్ అవలోకనం మరియు మౌలిక సదుపాయాలు',
    hardwareIntegration: 'హార్డ్‌వేర్ సమగ్రత',
    securityFeatures: 'భద్రతా లక్షణాలు',
    online: 'ఆన్‌లైన్',
    offline: 'ఆఫ్‌లైన్',
    
    // Common
    save: 'సేవ్ చేయండి',
    edit: 'సవరించండి',
    delete: 'తొలగించండి',
    view: 'చూడండి',
    close: 'మూసివేయండి',
    confirm: 'నిర్ధారించండి',
  },
  ta: {
    // Layout translations
    title: 'ஸ்மார்ட் மைன்ஸ்',
    subtitle: 'AI & ஆட்டோமேஷன்',
    dashboard: 'டாஷ்போர்டு',
    vehicleEntry: 'வாகன நுழைவு',
    aiDetection: 'AI கண்டறிதல்',
    weighbridge: 'வெயிபிரிட்ஜ்',
    inventory: 'சரக்கு',
    customers: 'வாடிக்கையாளர்கள்',
    employees: 'ஊழியர்கள்',
    billing: 'பில்லிங்',
    reports: 'அறிக்கைகள்',
    system: 'அமைப்பு',
    role: 'பங்கு',
    language: 'மொழி',
    logout: 'வெளியேறு',
    search: 'தேடு...',
    
    // Dashboard translations
    totalVehicles: 'மொத்த வாகனங்கள்',
    activeOperations: 'செயலில் உள்ள நடவடிக்கைகள்',
    todayRevenue: 'இன்றைய வருவாய்',
    pendingBills: 'நிலுவையில் உள்ள பில்கள்',
    recentActivities: 'சமீபத்திய நடவடிக்கைகள்',
    quickActions: 'விரைவு செயல்கள்',
    registerVehicle: 'வாகனம் பதிவு செய்',
    newWeighment: 'புதிய எடை',
    generateBill: 'பில் உருவாக்கு',
    viewReports: 'அறிக்கைகளை பார்',
    
    // Inventory translations
    stockOverview: 'பங்கு கண்ணோட்டம்',
    totalItems: 'மொத்த பொருட்கள்',
    lowStock: 'குறைந்த பங்கு',
    outOfStock: 'பங்கு இல்லை',
    addNewItem: 'புதிய பொருள் சேர்',
    materialName: 'பொருள் பெயர்',
    availableQuantity: 'கிடைக்கக்கூடிய அளவு',
    shiftedQuantity: 'மாற்றப்பட்ட அளவு',
    remainingStock: 'மீதமுள்ள பங்கு',
    unit: 'அலகு',
    location: 'இடம்',
    submit: 'சமர்ப்பிக்கவும்',
    cancel: 'ரத்து செய்',
    actions: 'செயல்கள்',
    availableItems: 'கிடைக்கக்கூடிய பொருட்கள்',
    shiftedItems: 'மாற்றப்பட்ட பொருட்கள்',
    addEntry: 'உள்ளீடு சேர்',
    manualEntry: 'கைமுறை உள்ளீடு',
    
    // Customer Management translations
    customerManagement: 'வாடிக்கையாளர் மேலாண்மை',
    manageCustomerAccounts: 'வாடிக்கையாளர் கணக்குகள் மற்றும் உறவுகளை நிர்வகிக்கவும்',
    addCustomer: 'வாடிக்கையாளர் சேர்',
    totalCustomers: 'மொத்த வாடிக்கையாளர்கள்',
    totalOrders: 'மொத்த ஆர்டர்கள்',
    totalRevenue: 'மொத்த வருவாய்',
    recentActivity: 'சமீபத்திய செயல்பாடு',
    allCustomers: 'அனைத்து வாடிக்கையாளர்கள்',
    customerId: 'வாடிக்கையாளர் ID',
    company: 'நிறுவனம்',
    contact: 'தொடர்பு',
    phone: 'தொலைபேசி',
    orders: 'ஆர்டர்கள்',
    value: 'மதிப்பு',
    status: 'நிலை',
    active: 'செயலில்',
    inactive: 'செயலில்லை',
    newOrderPlaced: 'புதிய ஆர்டர் வழங்கப்பட்டது',
    paymentReceived: 'கட்டணம் பெறப்பட்டது',
    deliveryCompleted: 'விநியோகம் நிறைவடைந்தது',
    
    // Billing translations
    billingInvoicing: 'பில்லிங் & விலைப்பட்டியல்',
    manageInvoicesPayment: 'விலைப்பட்டியல்கள் மற்றும் கட்டண கண்காணிப்பை நிர்வகிக்கவும்',
    createInvoice: 'விலைப்பட்டியல் உருவாக்கு',
    totalInvoices: 'மொத்த விலைப்பட்டியல்கள்',
    paidInvoices: 'செலுத்தப்பட்ட விலைப்பட்டியல்கள்',
    pending: 'நிலுவையில்',
    thisMonth: 'இம்மாதம்',
    collected: 'சேகரிக்கப்பட்டது',
    outstanding: 'நிலுவை',
    allInvoices: 'அனைத்து விலைப்பட்டியல்கள்',
    invoiceId: 'விலைப்பட்டியல் ID',
    vehicle: 'வாகனம்',
    material: 'பொருள்',
    netWeight: 'நிகர எடை',
    rate: 'விகிதம்',
    amount: 'தொகை',
    date: 'தேதி',
    dueDate: 'கடைசி தேதி',
    generate: 'உருவாக்கு',
    print: 'அச்சிடு',
    paid: 'செலுத்தப்பட்டது',
    
    // Employee translations
    employeeManagement: 'ஊழியர் மேலாண்மை',
    manageStaffRoles: 'பணியாளர் உறுப்பினர்கள் மற்றும் பங்கு நியமனங்களை நிர்வகிக்கவும்',
    addEmployee: 'ஊழியர் சேர்',
    totalEmployees: 'மொத்த ஊழியர்கள்',
    operators: 'இயக்குநர்கள்',
    departments: 'துறைகள்',
    employeeDirectory: 'ஊழியர் அடைவு',
    allEmployees: 'அனைத்து ஊழியர்கள்',
    employeeId: 'ஊழியர் ID',
    name: 'பெயர்',
    department: 'துறை',
    email: 'மின்னஞ்சல்',
    joinDate: 'சேர்ந்த தேதி',
    rolePermissions: 'பங்கு அனுமதிகள்',
    permissions: 'அனுமதிகள்',
    
    // Vehicle Entry translations
    activeVehicles: 'செயலில் உள்ள வாகனங்கள்',
    startScanning: 'ஸ்கேனிங் தொடங்கு',
    recentEntries: 'சமீபத்திய உள்ளீடுகள்',
    vehicleId: 'வாகன ID',
    driver: 'ஓட்டுநர்',
    weight: 'எடை',
    time: 'நேரம்',
    type: 'வகை',
    inTransit: 'பயணத்தில்',
    loading: 'ஏற்றுகிறது',
    weighing: 'எடை போடுகிறது',
    unloading: 'இறக்குகிறது',
    manual: 'கையேடு',
    nfcTag: 'NFC குறிச்சொல்',
    lastEntry: 'கடைசி உள்ளீடு',
    
    // Weighbridge translations
    weighbridgeManagement: 'வெயிபிரிட்ஜ் மேலாண்மை',
    realTimeWeighing: 'நிகழ்நேர வாகன எடை மற்றும் கண்காணிப்பு',
    vehiclesToday: 'இன்றைய வாகனங்கள்',
    totalWeight: 'மொத்த எடை',
    avgWeight: 'சராசரி எடை',
    recentWeighings: 'சமீபத்திய எடைகள்',
    tareWeight: 'வெற்று எடை',
    grossWeight: 'மொத்த எடை',
    startWeighing: 'எடை தொடங்கு',
    complete: 'நிறைவு',
    currentWeight: 'தற்போதைய எடை',
    
    // Product Detection translations
    aiProductDetection: 'AI தயாரிப்பு கண்டறிதல்',
    materialIdentification: 'நிகழ்நேர பொருள் அடையாளம் மற்றும் தர பகுப்பாய்வு',
    confidence: 'நம்பிக்கை',
    recentDetections: 'சமீபத்திய கண்டறிதல்கள்',
    batch: 'தொகுதி',
    quality: 'தரம்',
    scan: 'ஸ்கேன்',
    fraudAlert: 'மோசடி எச்சரிக்கை',
    high: 'உயர்ந்த',
    medium: 'நடுத்தர',
    low: 'குறைந்த',
    
    // Reports translations
    productionReports: 'உற்பத்தி அறிக்கைகள்',
    analyticsInsights: 'விரிவான பகுப்பாய்வு மற்றும் நுண்ணறிவுகள்',
    downloadReport: 'அறிக்கையை பதிவிறக்கு',
    keyInsights: 'முக்கிய நுண்ணறிவுகள்',
    monthlyTrends: 'மாதாந்திர போக்குகள்',
    performance: 'செயல்திறன்',
    productionData: 'உற்பத்தி தரவு',
    detectionAccuracy: 'கண்டறிதல் துல்லியம்',
    materialDistribution: 'பொருள் விநியோகம்',
    
    // System Architecture translations
    systemArchitecture: 'கணினி கட்டமைப்பு',
    systemOverview: 'முழுமையான அமைப்பு கண்ணோட்டம் மற்றும் உள்கட்டமைப்பு',
    hardwareIntegration: 'வன்பொருள் ஒருங்கிணைப்பு',
    securityFeatures: 'பாதுகாப்பு அம்சங்கள்',
    online: 'ஆன்லைன்',
    offline: 'ஆஃப்லைன்',
    
    // Common
    save: 'சேமி',
    edit: 'திருத்து',
    delete: 'நீக்கு',
    view: 'பார்',
    close: 'மூடு',
    confirm: 'உறுதிப்படுத்து',
  }
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem('appLanguage') || 'en');

  useEffect(() => {
    localStorage.setItem('appLanguage', language);
  }, [language]);

  const t = translations[language];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
